---
swagger: "2.0"
info:
  description: "Best Weather API\n"
  version: "1.0.2"
  title: "Best Weather API"
host: "virtserver.swaggerhub.com"
basePath: "/arebest/BestWeatherAPI/1.0.1"
schemes:
- "https"
- "http"
paths:
  /weather:
    get:
      summary: "Get the Weather"
      description: "Get the Weather from wherever you want"
      operationId: "weatherGET"
      parameters: []
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Default"
definitions: {}
