---
swagger: "2.0"
info:
  description: "Best Weather API\n"
  version: "1.1.0"
  title: "Best Weather API"
schemes:
- "https"
- "http"
paths:
  /weather/{location}:
    get:
      summary: "Get the Weather"
      description: "Get the Weather from wherever you want"
      operationId: "withLocation"
      parameters:
      - name: "location"
        in: "path"
        description: "Location to get weather"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Default"
    x-swagger-router-controller: "weather"
definitions: {}
