---
swagger: "2.0"
info:
  description: "Best Weather API\n"
  version: "1.1.1"
  title: "Best Weather API"
tags:
- name: "weather"
  description: "Weather operations"
schemes:
- "https"
- "http"
paths:
  /weather/{location}:
    get:
      tags:
      - "weather"
      summary: "Get the Weather"
      description: "Get the Weather from wherever you want"
      operationId: "withLocation"
      produces:
      - "application/json"
      parameters:
      - name: "location"
        in: "path"
        description: "Location to get weather"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Weather"
definitions: {}
